services:
  # Spring Boot Application
  app-supplychain:
    build: .
    container_name: app-supplychain
    ports:
      - "8080:8080"
    environment:

      - SPRING_DATASOURCE_URL=jdbc:mysql://db-supplychain:3306/supplychain_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_LIQUIBASE_ENABLED=true
    depends_on:
      - db-supplychain

  #mysql
  db-supplychain:
    image: mysql:8.0
    container_name: db-supplychain
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supplychain_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  #SonarQube
  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
    volumes:
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_logs:/opt/sonarqube/logs

  # Jenkins
  jenkins:
      image: jenkins/jenkins:lts
      container_name: jenkins

      user: root
      ports:
        - "9090:8080"
        - "50000:50000"
      volumes:

        - /var/run/docker.sock:/var/run/docker.sock
        - jenkins_home:/var/jenkins_home
      depends_on:
        - sonarqube


volumes:
  mysql_data:
  sonar_data:
  sonar_extensions:
  sonar_logs:
  jenkins_home: